-- MySQL Script generated by MySQL Workbench
-- Fri Sep 16 22:20:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AzcMe_Uam
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AzcMe_Uam` ;

-- -----------------------------------------------------
-- Schema AzcMe_Uam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AzcMe_Uam` DEFAULT CHARACTER SET utf8 ;
USE `AzcMe_Uam` ;

-- -----------------------------------------------------
-- Table `AzcMe_Uam`.`PalabraClave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AzcMe_Uam`.`PalabraClave` (
  `idPalabraClave` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPalabraClave`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AzcMe_Uam`.`TipoMaterial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AzcMe_Uam`.`TipoMaterial` (
  `idTipoMaterial` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AzcMe_Uam`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AzcMe_Uam`.`Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `ApellidoP` VARCHAR(45) NULL,
  `ApellidoM` VARCHAR(45) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AzcMe_Uam`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AzcMe_Uam`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(16) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoP` VARCHAR(45) NULL,
  `apellidoM` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AzcMe_Uam`.`UEA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AzcMe_Uam`.`UEA` (
  `idUEA` INT NOT NULL AUTO_INCREMENT,
  `nombreUEA` VARCHAR(45) NOT NULL,
  `claveUEA` INT NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idUEA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AzcMe_Uam`.`Temario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AzcMe_Uam`.`Temario` (
  `idTemario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `UEA_idUEA` INT NOT NULL,
  PRIMARY KEY (`idTemario`),
  CONSTRAINT `fk_Temario_UEA1`
    FOREIGN KEY (`UEA_idUEA`)
    REFERENCES `AzcMe_Uam`.`UEA` (`idUEA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AzcMe_Uam`.`Tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AzcMe_Uam`.`Tema` (
  `idTema` INT NOT NULL auto_increment,
  `Nombre` VARCHAR(45) NULL,
  `Temario_idTemario` INT NOT NULL,
  PRIMARY KEY (`idTema`),
  CONSTRAINT `fk_Tema_Temario1`
    FOREIGN KEY (`Temario_idTemario`)
    REFERENCES `AzcMe_Uam`.`Temario` (`idTemario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AzcMe_Uam`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AzcMe_Uam`.`Material` (
  `idMaterial` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `URL` VARCHAR(45) NULL,
  `FechaPublicacion` DATE NULL,
  `Tema_idTema` INT NOT NULL,
  PRIMARY KEY (`idMaterial`),
  CONSTRAINT `fk_Material_Tema1`
    FOREIGN KEY (`Tema_idTema`)
    REFERENCES `AzcMe_Uam`.`Tema` (`idTema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AzcMe_Uam`.`Material_has_Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AzcMe_Uam`.`Material_has_Autor` (
  `id_M_A` INT NOT NULL AUTO_INCREMENT,
  `Material_idMaterial` INT NOT NULL,
  `Autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`id_M_A`),
  CONSTRAINT `fk_Material_has_Autor_Material`
    FOREIGN KEY (`Material_idMaterial`)
    REFERENCES `AzcMe_Uam`.`Material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Material_has_Autor_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `AzcMe_Uam`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AzcMe_Uam`.`PalabraClave_has_Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AzcMe_Uam`.`PalabraClave_has_Material` (
  `id_PC_M` INT NOT NULL AUTO_INCREMENT,
  `PalabraClave_idPalabraClave` INT NOT NULL,
  `Material_idMaterial` INT NOT NULL,
  PRIMARY KEY (`id_PC_M`),
  CONSTRAINT `fk_PalabraClave_has_Material_PalabraClave1`
    FOREIGN KEY (`PalabraClave_idPalabraClave`)
    REFERENCES `AzcMe_Uam`.`PalabraClave` (`idPalabraClave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PalabraClave_has_Material_Material1`
    FOREIGN KEY (`Material_idMaterial`)
    REFERENCES `AzcMe_Uam`.`Material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AzcMe_Uam`.`Material_has_TipoMaterial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AzcMe_Uam`.`Material_has_TipoMaterial` (
  `Material_idMaterial` INT NOT NULL,
  `TipoMaterial_idTipoMaterial` INT NOT NULL,
  `idM_TM` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idM_TM`),
  CONSTRAINT `fk_Material_has_TipoMaterial_Material1`
    FOREIGN KEY (`Material_idMaterial`)
    REFERENCES `AzcMe_Uam`.`Material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Material_has_TipoMaterial_TipoMaterial1`
    FOREIGN KEY (`TipoMaterial_idTipoMaterial`)
    REFERENCES `AzcMe_Uam`.`TipoMaterial` (`idTipoMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


Insert into admin (usuario,contrasena,nombre,apellidoP,apellidoM) values ('laloalex','EduardoA','Eduardo Alejandro', 'Rodríguez','Cestelos');
Insert into admin (usuario,contrasena,nombre,apellidoP,apellidoM) values ('alex','Alex_3','Alejandro', 'Rodríguez','Cestelos');
Insert into autor (Nombre,ApellidoP,ApellidoM) values ('Eduardo Alejandro','Rodríguez','Cestelos');
Insert into autor (Nombre,ApellidoP,ApellidoM) values ('Leonardo Daniel', 'Sánchez', 'Martínez');
Insert into palabraclave (Descripcion) values ('BD');
Insert into palabraclave (Descripcion) values ('Algebra Relacional');
Insert into palabraclave (Descripcion) values ('DER');
Insert into UEA (nombreUEA, claveUEA, descripcion) values ('Base de Datos', '1151046', 'En esta UEA el alumno será capaz de aprender lo basico de las Bases de Datos');
Insert into temario (Nombre, UEA_idUEA) values ('Base de Datos 1', '1');
Insert into tipomaterial (descripcion) values ('PDFs');
Insert into tipomaterial (descripcion) values ('Video Youtube');
Insert into tipomaterial (descripcion) values ('Libro BiDiUAM');
Insert into tema (Nombre, Temario_idTemario) values ('algebra relacional', '1');
Insert into tema (Nombre, Temario_idTemario) values ('diagrama entidad relacion', '1');

/*
Set foreign_key_checks = 0;
Set foreign_key_checks = 1;
*/